"use client";

import { useEffect, useMemo, useRef, useState, useCallback } from "react";
import { createPortal } from "react-dom";
import {
  BookOpen,
  ChevronLeft,
  ChevronRight,
  Download,
  Minus,
  Plus,
  Square,
  X,
} from "lucide-react";
import {
  openFlipbookDocument,
  prefetchPageImage,
  type FlipbookDoc,
  type FlipbookPage,
} from "@/lib/pdf-flipbook";

type Props = {
  fileUrl: string;
  fileName: string;
  title: string;
  /** Matches the folder under public/catalog/<catalogId>/ generated by
   *  scripts/compress-catalog-pdf.mjs. When present, the viewer loads
   *  pre-rendered static images instead of parsing the PDF client-side. */
  catalogId?: string;
  /** Absolute or relative URL to a pre-rendered manifest.json (CMS uploads). */
  manifestUrl?: string;
  onClose: () => void;
};

const SLIDE_MS = 320;
/** Pages ahead of the current view to warm in the background (not the whole book). */
const PREFETCH_AHEAD = 4;
const ZOOM_STEPS = [100, 125, 150, 175, 200, 250] as const;
const ZOOM_MIN = ZOOM_STEPS[0];
const ZOOM_MAX = ZOOM_STEPS[ZOOM_STEPS.length - 1]!;

function nextZoom(current: number, dir: 1 | -1) {
  if (dir === 1) {
    return ZOOM_STEPS.find((step) => step > current) ?? ZOOM_MAX;
  }
  return [...ZOOM_STEPS].reverse().find((step) => step < current) ?? ZOOM_MIN;
}

type ViewMode = 1 | 2;

export function CatalogFlipbookModal({
  fileUrl,
  fileName,
  title,
  catalogId,
  manifestUrl,
  onClose,
}: Props) {
  const [doc, setDoc] = useState<FlipbookDoc | null>(null);
  const [numPages, setNumPages] = useState(0);
  const [pageCache, setPageCache] = useState<Record<number, FlipbookPage>>({});
  const [ready, setReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [downloadProgress, setDownloadProgress] = useState({ loaded: 0, total: 0 });
  const [viewMode, setViewMode] = useState<ViewMode>(() =>
    typeof window !== "undefined" && window.innerWidth >= 768 ? 2 : 1,
  );
  const [modeLocked, setModeLocked] = useState(false);
  const [index, setIndex] = useState(0);
  const [slideDir, setSlideDir] = useState<"next" | "prev" | null>(null);
  const [slideKey, setSlideKey] = useState(0);
  const [turning, setTurning] = useState(false);
  const [zoom, setZoom] = useState(100);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [dragging, setDragging] = useState(false);
  const slideTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const dragRef = useRef<{
    pointerId: number;
    startX: number;
    startY: number;
    originX: number;
    originY: number;
    moved: boolean;
  } | null>(null);

  useEffect(() => {
    return () => {
      if (slideTimer.current) clearTimeout(slideTimer.current);
    };
  }, []);

  const addPages = useCallback((entries: Array<[number, FlipbookPage]>) => {
    if (entries.length === 0) return;
    setPageCache((prev) => {
      const next = { ...prev };
      for (const [i, p] of entries) next[i] = p;
      return next;
    });
  }, []);

  useEffect(() => {
    let cancelled = false;
    let docHandle: FlipbookDoc | null = null;

    openFlipbookDocument(
      fileUrl,
      { catalogId, manifestUrl },
      (loaded, total) => {
        if (!cancelled) setDownloadProgress({ loaded, total });
      },
    )
      .then(async (handle) => {
        if (cancelled) {
          handle.destroy();
          return;
        }
        docHandle = handle;
        setDoc(handle);
        setNumPages(handle.numPages);

        const firstCount = Math.min(2, handle.numPages);
        const first = await Promise.all(
          Array.from({ length: firstCount }, (_, i) =>
            handle.getPage(i).then((p) => [i, p] as [number, FlipbookPage]),
          ),
        );
        if (cancelled) return;
        addPages(first);
        setReady(true);
        for (const [, page] of first) prefetchPageImage(page.url);
        const aheadEnd = Math.min(firstCount + PREFETCH_AHEAD, handle.numPages);
        for (let i = firstCount; i < aheadEnd; i++) {
          handle
            .getPage(i)
            .then((p) => {
              if (cancelled) return;
              addPages([[i, p]]);
              prefetchPageImage(p.url);
            })
            .catch(() => {});
        }
      })
      .catch((err) => {
        if (!cancelled) {
          console.error(err);
          setError("เปิดไฟล์ไม่สำเร็จ ลองดาวน์โหลดไปดูแทนได้");
        }
      });

    return () => {
      cancelled = true;
      docHandle?.destroy();
    };
  }, [fileUrl, catalogId, manifestUrl, addPages]);

  const perView = viewMode;
  const maxIndex = Math.max(0, numPages - perView);
  const safeIndex = Math.min(index, maxIndex);
  const visibleIndices = useMemo(
    () =>
      Array.from({ length: perView }, (_, i) => safeIndex + i).filter(
        (pageIndex) => pageIndex >= 0 && pageIndex < numPages,
      ),
    [perView, safeIndex, numPages],
  );

  const ensurePagesReady = useCallback(
    async (start: number, count: number) => {
      if (!doc) return;
      const visible = Array.from({ length: count }, (_, i) => start + i).filter(
        (i) => i >= 0 && i < numPages,
      );
      const need = visible.filter((i) => !(i in pageCache));
      if (need.length > 0) {
        const rendered = await Promise.all(
          need.map((i) => doc.getPage(i).then((p) => [i, p] as [number, FlipbookPage])),
        );
        addPages(rendered);
        for (const [, page] of rendered) prefetchPageImage(page.url);
      }
      for (let i = start + count; i < Math.min(start + count + PREFETCH_AHEAD, numPages); i++) {
        if (i in pageCache) {
          prefetchPageImage(pageCache[i]!.url);
          continue;
        }
        doc
          .getPage(i)
          .then((p) => {
            addPages([[i, p]]);
            prefetchPageImage(p.url);
          })
          .catch(() => {});
      }
    },
    [doc, numPages, pageCache, addPages],
  );

  // Default to 2-up on desktop, 1-up on mobile — until the user toggles.
  useEffect(() => {
    if (modeLocked) return;
    function syncDefault() {
      const next: ViewMode = window.innerWidth >= 768 ? 2 : 1;
      setViewMode(next);
      void ensurePagesReady(safeIndex, next);
    }
    window.addEventListener("resize", syncDefault);
    return () => window.removeEventListener("resize", syncDefault);
  }, [modeLocked, ensurePagesReady, safeIndex]);

  const goTo = useCallback(
    async (next: number, dir: "next" | "prev") => {
      if (!doc || turning) return;
      const clamped = Math.max(0, Math.min(next, maxIndex));
      if (clamped === safeIndex) return;
      setTurning(true);
      await ensurePagesReady(clamped, perView);
      setPan({ x: 0, y: 0 });
      setSlideDir(dir);
      setSlideKey((k) => k + 1);
      setIndex(clamped);
      if (slideTimer.current) clearTimeout(slideTimer.current);
      slideTimer.current = setTimeout(() => {
        setTurning(false);
        setSlideDir(null);
        slideTimer.current = null;
      }, SLIDE_MS);
    },
    [doc, turning, safeIndex, maxIndex, ensurePagesReady, perView],
  );

  const goNext = useCallback(() => {
    const step = Math.min(perView, maxIndex - safeIndex);
    if (step <= 0) return;
    void goTo(safeIndex + step, "next");
  }, [goTo, safeIndex, maxIndex, perView]);

  const goPrev = useCallback(() => {
    const step = Math.min(perView, safeIndex);
    if (step <= 0) return;
    void goTo(safeIndex - step, "prev");
  }, [goTo, safeIndex, perView]);

  function setMode(mode: ViewMode) {
    setModeLocked(true);
    setViewMode(mode);
    const nextIndex = mode === 2 ? Math.floor(index / 2) * 2 : index;
    if (nextIndex !== index) setIndex(nextIndex);
    void ensurePagesReady(nextIndex, mode);
  }

  useEffect(() => {
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
      if (e.key === "ArrowRight") goNext();
      if (e.key === "ArrowLeft") goPrev();
      if (e.key === "+" || e.key === "=") {
        e.preventDefault();
        setZoom((z) => nextZoom(z, 1));
      }
      if (e.key === "-" || e.key === "_") {
        e.preventDefault();
        setZoom((z) => nextZoom(z, -1));
      }
      if (e.key === "0") setZoom(ZOOM_MIN);
    }
    window.addEventListener("keydown", onKey);
    return () => {
      document.body.style.overflow = prevOverflow;
      window.removeEventListener("keydown", onKey);
    };
  }, [onClose, goNext, goPrev]);

  const touchStartX = useRef<number | null>(null);
  function onTouchStart(e: React.TouchEvent) {
    if (zoom > 100 || e.touches.length > 1) {
      touchStartX.current = null;
      return;
    }
    touchStartX.current = e.touches[0]?.clientX ?? null;
  }
  function onTouchEnd(e: React.TouchEvent) {
    if (touchStartX.current === null) return;
    const dx = (e.changedTouches[0]?.clientX ?? 0) - touchStartX.current;
    touchStartX.current = null;
    if (Math.abs(dx) < 40) return;
    if (dx < 0) goNext();
    else goPrev();
  }

  function zoomBy(dir: 1 | -1) {
    setZoom((z) => {
      const next = nextZoom(z, dir);
      if (next === ZOOM_MIN) setPan({ x: 0, y: 0 });
      return next;
    });
  }

  function onPageClick() {
    if (dragRef.current?.moved) return;
    setZoom((z) => {
      if (z >= ZOOM_MAX) {
        setPan({ x: 0, y: 0 });
        return ZOOM_MIN;
      }
      return nextZoom(z, 1);
    });
  }

  function onPagePointerDown(e: React.PointerEvent) {
    if (e.button !== 0) return;
    dragRef.current = {
      pointerId: e.pointerId,
      startX: e.clientX,
      startY: e.clientY,
      originX: pan.x,
      originY: pan.y,
      moved: false,
    };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  }

  function onPagePointerMove(e: React.PointerEvent) {
    const drag = dragRef.current;
    if (!drag || drag.pointerId !== e.pointerId) return;
    const dx = e.clientX - drag.startX;
    const dy = e.clientY - drag.startY;
    if (!drag.moved && Math.hypot(dx, dy) < 6) return;
    drag.moved = true;
    if (zoom <= 100) return;
    setDragging(true);
    setPan({ x: drag.originX + dx, y: drag.originY + dy });
  }

  function onPagePointerUp(e: React.PointerEvent) {
    const drag = dragRef.current;
    if (!drag || drag.pointerId !== e.pointerId) return;
    const wasDrag = drag.moved;
    dragRef.current = null;
    setDragging(false);
    if (!wasDrag) onPageClick();
  }

  function onPageWheel(e: React.WheelEvent) {
    if (!e.ctrlKey && Math.abs(e.deltaY) < 40) return;
    e.preventDefault();
    zoomBy(e.deltaY < 0 ? 1 : -1);
  }

  const aspect = useMemo(() => {
    const first = pageCache[0];
    if (!first) return 1 / 1.414;
    const ratio = first.width / first.height;
    return perView === 2 ? ratio * 2 : ratio;
  }, [pageCache, perView]);

  const rangeLabel =
    numPages > 0
      ? visibleIndices.length > 1
        ? `${visibleIndices[0]! + 1}-${visibleIndices[visibleIndices.length - 1]! + 1} / ${numPages}`
        : `${safeIndex + 1} / ${numPages}`
      : "";

  const loadPercent = useMemo(() => {
    if (ready) return 100;
    if (numPages > 0) return 96;
    if (downloadProgress.total > 0) {
      return Math.max(4, Math.min(92, Math.round((downloadProgress.loaded / downloadProgress.total) * 92)));
    }
    return 4;
  }, [ready, numPages, downloadProgress]);

  const slideAnimClass =
    slideDir === "next"
      ? "animate-catalog-slide-next"
      : slideDir === "prev"
        ? "animate-catalog-slide-prev"
        : "";

  if (typeof document === "undefined") return null;

  return createPortal(
    <div
      className="fixed inset-0 z-[90] flex flex-col bg-navy/95 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-label={title}
    >
      <div className="flex items-center justify-between gap-3 px-4 py-3 sm:px-6">
        <h2 className="min-w-0 truncate text-sm font-semibold text-white sm:text-base">
          {title}
        </h2>
        <div className="flex shrink-0 items-center gap-2">
          <div
            className="hidden items-center rounded-full bg-white/10 p-0.5 sm:inline-flex"
            role="group"
            aria-label="สลับโหมดการดู"
          >
            <button
              type="button"
              onClick={() => setMode(1)}
              aria-pressed={perView === 1}
              title="ดูหน้าเดียว"
              className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1.5 text-xs font-medium transition ${
                perView === 1
                  ? "bg-white text-navy"
                  : "text-white/80 hover:bg-white/10"
              }`}
            >
              <Square className="h-3.5 w-3.5" />
              1 หน้า
            </button>
            <button
              type="button"
              onClick={() => setMode(2)}
              aria-pressed={perView === 2}
              title="ดู 2 หน้าพร้อมกัน"
              className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1.5 text-xs font-medium transition ${
                perView === 2
                  ? "bg-white text-navy"
                  : "text-white/80 hover:bg-white/10"
              }`}
            >
              <BookOpen className="h-3.5 w-3.5" />
              2 หน้า
            </button>
          </div>
          <a
            href={fileUrl}
            download={fileName}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 rounded-full bg-brand-red px-3.5 py-2 text-xs font-semibold text-white transition hover:bg-brand-red-soft sm:text-sm"
          >
            <Download className="h-3.5 w-3.5" />
            ดาวน์โหลด
          </a>
          <button
            type="button"
            onClick={onClose}
            aria-label="ปิด"
            className="rounded-full bg-white/10 p-2 text-white transition hover:bg-white/20"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
      </div>

      <div
        className="relative flex min-h-0 flex-1 items-center justify-center overflow-hidden px-10 pb-2 sm:px-14"
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
      >
        {error ? (
          <p className="max-w-xs text-center text-sm text-white/80">{error}</p>
        ) : !ready ? (
          <div className="flex w-full max-w-xs flex-col items-center gap-3 text-white/80">
            <p className="text-sm">กำลังเปิดไฟล์...</p>
            <div className="h-2 w-full overflow-hidden rounded-full bg-white/15">
              <div
                className="h-full rounded-full bg-brand-red transition-[width] duration-200 ease-out"
                style={{ width: `${loadPercent}%` }}
              />
            </div>
            <p className="tabular-nums text-xs text-white/60">{loadPercent}%</p>
          </div>
        ) : (
          <>
            <button
              type="button"
              onClick={goPrev}
              disabled={safeIndex <= 0 || turning}
              aria-label="หน้าก่อนหน้า"
              className="absolute left-1 top-1/2 z-20 -translate-y-1/2 rounded-full bg-white/10 p-2 text-white transition hover:bg-white/20 disabled:opacity-30 sm:left-3"
            >
              <ChevronLeft className="h-6 w-6" />
            </button>

            <div
              key={slideKey}
              className={`relative mx-auto h-full max-h-full overflow-hidden ${slideAnimClass}`}
              style={{
                width: "auto",
                maxWidth: perView === 2 ? "min(100%, 1200px)" : "min(100%, calc(100vw - 7rem))",
                aspectRatio: aspect,
              }}
              onWheel={onPageWheel}
            >
              <div
                className="absolute inset-0 flex origin-center gap-0.5 will-change-transform"
                style={{
                  transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom / 100})`,
                  cursor: dragging ? "grabbing" : zoom > 100 ? "grab" : "zoom-in",
                  transition: dragging ? "none" : "transform 180ms ease-out",
                }}
                onPointerDown={onPagePointerDown}
                onPointerMove={onPagePointerMove}
                onPointerUp={onPagePointerUp}
                onPointerCancel={onPagePointerUp}
              >
                {visibleIndices.map((pageIndex, i) => (
                  <PageFace
                    key={pageIndex}
                    page={pageCache[pageIndex]}
                    priority={i === 0}
                  />
                ))}
              </div>
              <div className="pointer-events-none absolute bottom-2 left-2 z-10 rounded-full bg-navy/70 px-2.5 py-1 text-xs font-semibold tabular-nums text-white shadow-sm">
                {zoom}%
              </div>
            </div>

            <button
              type="button"
              onClick={goNext}
              disabled={safeIndex >= maxIndex || turning}
              aria-label="หน้าถัดไป"
              className="absolute right-1 top-1/2 z-20 -translate-y-1/2 rounded-full bg-white/10 p-2 text-white transition hover:bg-white/20 disabled:opacity-30 sm:right-3"
            >
              <ChevronRight className="h-6 w-6" />
            </button>
          </>
        )}
      </div>

      {ready ? (
        <div className="flex items-center justify-center gap-3 pb-4">
          <div
            className="inline-flex items-center rounded-full bg-white/10 p-0.5 sm:hidden"
            role="group"
            aria-label="สลับโหมดการดู"
          >
            <button
              type="button"
              onClick={() => setMode(1)}
              aria-pressed={perView === 1}
              className={`rounded-full px-2.5 py-1 text-xs font-medium transition ${
                perView === 1 ? "bg-white text-navy" : "text-white/80"
              }`}
            >
              1 หน้า
            </button>
            <button
              type="button"
              onClick={() => setMode(2)}
              aria-pressed={perView === 2}
              className={`rounded-full px-2.5 py-1 text-xs font-medium transition ${
                perView === 2 ? "bg-white text-navy" : "text-white/80"
              }`}
            >
              2 หน้า
            </button>
          </div>
          <p className="text-center text-xs text-white/60 sm:text-sm">{rangeLabel}</p>
          <div
            className="inline-flex items-center rounded-full bg-white/10 p-0.5"
            role="group"
            aria-label="ซูมหน้า"
          >
            <button
              type="button"
              onClick={() => zoomBy(-1)}
              disabled={zoom <= ZOOM_MIN}
              aria-label="ซูมออก"
              className="rounded-full p-1.5 text-white/80 transition hover:bg-white/10 disabled:opacity-30"
            >
              <Minus className="h-3.5 w-3.5" />
            </button>
            <span className="min-w-10 px-1 text-center text-xs font-semibold tabular-nums text-white">
              {zoom}%
            </span>
            <button
              type="button"
              onClick={() => zoomBy(1)}
              disabled={zoom >= ZOOM_MAX}
              aria-label="ซูมเข้า"
              className="rounded-full p-1.5 text-white/80 transition hover:bg-white/10 disabled:opacity-30"
            >
              <Plus className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>
      ) : null}
    </div>,
    document.body,
  );
}

function PageFace({
  page,
  priority = false,
}: {
  page: FlipbookPage | undefined;
  priority?: boolean;
}) {
  const [loaded, setLoaded] = useState(false);

  if (!page) {
    return (
      <div className="h-full w-full flex-1 animate-pulse rounded-sm bg-white/10" />
    );
  }

  return (
    <div className="relative h-full w-full flex-1">
      {loaded ? null : (
        <div className="absolute inset-0 animate-pulse rounded-sm bg-white/10" />
      )}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={page.url}
        alt=""
        fetchPriority={priority ? "high" : "low"}
        decoding="async"
        onLoad={() => setLoaded(true)}
        draggable={false}
        className={`pointer-events-none h-full w-full select-none rounded-sm bg-white object-contain shadow-2xl transition-opacity duration-200 ${
          loaded ? "opacity-100" : "opacity-0"
        }`}
      />
    </div>
  );
}
