"use client";

import { useEffect, useMemo, useRef, useState, useCallback } from "react";
import { createPortal } from "react-dom";
import {
  BookOpen,
  ChevronLeft,
  ChevronRight,
  Download,
  Square,
  X,
} from "lucide-react";
import { openFlipbookDocument, type FlipbookDoc, type FlipbookPage } from "@/lib/pdf-flipbook";

type Props = {
  fileUrl: string;
  fileName: string;
  title: string;
  /** Matches the folder under public/catalog/<catalogId>/ generated by
   *  scripts/compress-catalog-pdf.mjs. When present, the viewer loads
   *  pre-rendered static images instead of parsing the PDF client-side. */
  catalogId?: string;
  /** Absolute or relative URL to a pre-rendered manifest.json (CMS uploads). */
  manifestUrl?: string;
  onClose: () => void;
};

const SLIDE_MS = 320;
/** How many pages ahead of the current view to keep pre-rendered in the background. */
const PREFETCH_AHEAD = 3;

type ViewMode = 1 | 2;

export function CatalogFlipbookModal({
  fileUrl,
  fileName,
  title,
  catalogId,
  manifestUrl,
  onClose,
}: Props) {
  const [doc, setDoc] = useState<FlipbookDoc | null>(null);
  const [numPages, setNumPages] = useState(0);
  const [pageCache, setPageCache] = useState<Record<number, FlipbookPage>>({});
  const [ready, setReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [downloadProgress, setDownloadProgress] = useState({ loaded: 0, total: 0 });
  const [viewMode, setViewMode] = useState<ViewMode>(1);
  const [modeLocked, setModeLocked] = useState(false);
  const [index, setIndex] = useState(0);
  const [slideDir, setSlideDir] = useState<"next" | "prev" | null>(null);
  const [slideKey, setSlideKey] = useState(0);
  const [turning, setTurning] = useState(false);
  const slideTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (slideTimer.current) clearTimeout(slideTimer.current);
    };
  }, []);

  const addPages = useCallback((entries: Array<[number, FlipbookPage]>) => {
    if (entries.length === 0) return;
    setPageCache((prev) => {
      const next = { ...prev };
      for (const [i, p] of entries) next[i] = p;
      return next;
    });
  }, []);

  useEffect(() => {
    let cancelled = false;
    let docHandle: FlipbookDoc | null = null;

    openFlipbookDocument(
      fileUrl,
      { catalogId, manifestUrl },
      (loaded, total) => {
        if (!cancelled) setDownloadProgress({ loaded, total });
      },
    )
      .then(async (handle) => {
        if (cancelled) {
          handle.destroy();
          return;
        }
        docHandle = handle;
        setDoc(handle);
        setNumPages(handle.numPages);

        // Show the very first page as fast as possible; the rest fills in
        // a beat later via background prefetch below.
        const firstBatch = Math.min(1, handle.numPages);
        const first = await Promise.all(
          Array.from({ length: firstBatch }, (_, i) =>
            handle.getPage(i).then((p) => [i, p] as [number, FlipbookPage]),
          ),
        );
        if (cancelled) return;
        addPages(first);
        setReady(true);

        for (let i = firstBatch; i < handle.numPages; i++) {
          if (cancelled) break;
          try {
            const p = await handle.getPage(i);
            if (cancelled) break;
            addPages([[i, p]]);
          } catch {
            // ignore background prefetch failures; page will retry on demand
          }
          await new Promise((r) => setTimeout(r, 0));
        }
      })
      .catch((err) => {
        if (!cancelled) {
          console.error(err);
          setError("เปิดไฟล์ไม่สำเร็จ ลองดาวน์โหลดไปดูแทนได้");
        }
      });

    return () => {
      cancelled = true;
      docHandle?.destroy();
    };
  }, [fileUrl, catalogId, manifestUrl, addPages]);

  // Default to 2-up on desktop, 1-up on mobile — until the user toggles.
  useEffect(() => {
    if (modeLocked) return;
    function syncDefault() {
      setViewMode(window.innerWidth >= 768 ? 2 : 1);
    }
    syncDefault();
    window.addEventListener("resize", syncDefault);
    return () => window.removeEventListener("resize", syncDefault);
  }, [modeLocked]);

  const perView = viewMode;
  const maxIndex = Math.max(0, numPages - perView);
  const safeIndex = Math.min(index, maxIndex);
  const visibleIndices = useMemo(
    () =>
      Array.from({ length: perView }, (_, i) => safeIndex + i).filter(
        (pageIndex) => pageIndex >= 0 && pageIndex < numPages,
      ),
    [perView, safeIndex, numPages],
  );

  const ensurePagesReady = useCallback(
    async (start: number, count: number) => {
      if (!doc) return;
      const need = Array.from({ length: count }, (_, i) => start + i).filter(
        (i) => i >= 0 && i < numPages && !(i in pageCache),
      );
      if (need.length > 0) {
        const rendered = await Promise.all(
          need.map((i) => doc.getPage(i).then((p) => [i, p] as [number, FlipbookPage])),
        );
        addPages(rendered);
      }
      for (let i = start + count; i < Math.min(start + count + PREFETCH_AHEAD, numPages); i++) {
        if (!(i in pageCache)) {
          doc
            .getPage(i)
            .then((p) => addPages([[i, p]]))
            .catch(() => {});
        }
      }
    },
    [doc, numPages, pageCache, addPages],
  );

  const goTo = useCallback(
    async (next: number, dir: "next" | "prev") => {
      if (!doc || turning) return;
      const clamped = Math.max(0, Math.min(next, maxIndex));
      if (clamped === safeIndex) return;
      setTurning(true);
      await ensurePagesReady(clamped, perView);
      setSlideDir(dir);
      setSlideKey((k) => k + 1);
      setIndex(clamped);
      if (slideTimer.current) clearTimeout(slideTimer.current);
      slideTimer.current = setTimeout(() => {
        setTurning(false);
        setSlideDir(null);
        slideTimer.current = null;
      }, SLIDE_MS);
    },
    [doc, turning, safeIndex, maxIndex, ensurePagesReady, perView],
  );

  const goNext = useCallback(() => {
    const step = Math.min(perView, maxIndex - safeIndex);
    if (step <= 0) return;
    void goTo(safeIndex + step, "next");
  }, [goTo, safeIndex, maxIndex, perView]);

  const goPrev = useCallback(() => {
    const step = Math.min(perView, safeIndex);
    if (step <= 0) return;
    void goTo(safeIndex - step, "prev");
  }, [goTo, safeIndex, perView]);

  function setMode(mode: ViewMode) {
    setModeLocked(true);
    setViewMode(mode);
    // Align to even index for tidy 2-up spreads when switching up.
    if (mode === 2) {
      setIndex((i) => Math.floor(i / 2) * 2);
    }
  }

  useEffect(() => {
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
      if (e.key === "ArrowRight") goNext();
      if (e.key === "ArrowLeft") goPrev();
    }
    window.addEventListener("keydown", onKey);
    return () => {
      document.body.style.overflow = prevOverflow;
      window.removeEventListener("keydown", onKey);
    };
  }, [onClose, goNext, goPrev]);

  const touchStartX = useRef<number | null>(null);
  function onTouchStart(e: React.TouchEvent) {
    touchStartX.current = e.touches[0]?.clientX ?? null;
  }
  function onTouchEnd(e: React.TouchEvent) {
    if (touchStartX.current === null) return;
    const dx = (e.changedTouches[0]?.clientX ?? 0) - touchStartX.current;
    touchStartX.current = null;
    if (Math.abs(dx) < 40) return;
    if (dx < 0) goNext();
    else goPrev();
  }

  const aspect = useMemo(() => {
    const first = pageCache[0];
    if (!first) return 1 / 1.414;
    const ratio = first.width / first.height;
    return perView === 2 ? ratio * 2 : ratio;
  }, [pageCache, perView]);

  const rangeLabel =
    numPages > 0
      ? visibleIndices.length > 1
        ? `${visibleIndices[0]! + 1}-${visibleIndices[visibleIndices.length - 1]! + 1} / ${numPages}`
        : `${safeIndex + 1} / ${numPages}`
      : "";

  const loadPercent = useMemo(() => {
    if (ready) return 100;
    if (numPages > 0) return 96;
    if (downloadProgress.total > 0) {
      return Math.max(4, Math.min(92, Math.round((downloadProgress.loaded / downloadProgress.total) * 92)));
    }
    return 4;
  }, [ready, numPages, downloadProgress]);

  const slideAnimClass =
    slideDir === "next"
      ? "animate-catalog-slide-next"
      : slideDir === "prev"
        ? "animate-catalog-slide-prev"
        : "";

  if (typeof document === "undefined") return null;

  return createPortal(
    <div
      className="fixed inset-0 z-[90] flex flex-col bg-navy/95 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-label={title}
    >
      <div className="flex items-center justify-between gap-3 px-4 py-3 sm:px-6">
        <h2 className="min-w-0 truncate text-sm font-semibold text-white sm:text-base">
          {title}
        </h2>
        <div className="flex shrink-0 items-center gap-2">
          <div
            className="hidden items-center rounded-full bg-white/10 p-0.5 sm:inline-flex"
            role="group"
            aria-label="สลับโหมดการดู"
          >
            <button
              type="button"
              onClick={() => setMode(1)}
              aria-pressed={perView === 1}
              title="ดูหน้าเดียว"
              className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1.5 text-xs font-medium transition ${
                perView === 1
                  ? "bg-white text-navy"
                  : "text-white/80 hover:bg-white/10"
              }`}
            >
              <Square className="h-3.5 w-3.5" />
              1 หน้า
            </button>
            <button
              type="button"
              onClick={() => setMode(2)}
              aria-pressed={perView === 2}
              title="ดู 2 หน้าพร้อมกัน"
              className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1.5 text-xs font-medium transition ${
                perView === 2
                  ? "bg-white text-navy"
                  : "text-white/80 hover:bg-white/10"
              }`}
            >
              <BookOpen className="h-3.5 w-3.5" />
              2 หน้า
            </button>
          </div>
          <a
            href={fileUrl}
            download={fileName}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 rounded-full bg-brand-red px-3.5 py-2 text-xs font-semibold text-white transition hover:bg-brand-red-soft sm:text-sm"
          >
            <Download className="h-3.5 w-3.5" />
            ดาวน์โหลด
          </a>
          <button
            type="button"
            onClick={onClose}
            aria-label="ปิด"
            className="rounded-full bg-white/10 p-2 text-white transition hover:bg-white/20"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
      </div>

      <div
        className="relative flex flex-1 items-center justify-center overflow-hidden px-3 pb-4 sm:px-8"
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
      >
        {error ? (
          <p className="max-w-xs text-center text-sm text-white/80">{error}</p>
        ) : !ready ? (
          <div className="flex w-full max-w-xs flex-col items-center gap-3 text-white/80">
            <p className="text-sm">กำลังเปิดไฟล์...</p>
            <div className="h-2 w-full overflow-hidden rounded-full bg-white/15">
              <div
                className="h-full rounded-full bg-brand-red transition-[width] duration-200 ease-out"
                style={{ width: `${loadPercent}%` }}
              />
            </div>
            <p className="tabular-nums text-xs text-white/60">{loadPercent}%</p>
          </div>
        ) : (
          <>
            <button
              type="button"
              onClick={goPrev}
              disabled={safeIndex <= 0 || turning}
              aria-label="หน้าก่อนหน้า"
              className="absolute left-1 top-1/2 z-20 -translate-y-1/2 rounded-full bg-white/10 p-2 text-white transition hover:bg-white/20 disabled:opacity-30 sm:left-3"
            >
              <ChevronLeft className="h-6 w-6" />
            </button>

            <div
              key={slideKey}
              className={`relative mx-auto w-full overflow-hidden ${slideAnimClass}`}
              style={{
                maxWidth: perView === 2 ? "min(92vw, 1000px)" : "min(92vw, 560px)",
                maxHeight: "80vh",
                aspectRatio: aspect,
              }}
            >
              <div className="absolute inset-0 flex gap-0.5">
                {visibleIndices.map((pageIndex) => (
                  <PageFace key={pageIndex} page={pageCache[pageIndex]} />
                ))}
              </div>
            </div>

            <button
              type="button"
              onClick={goNext}
              disabled={safeIndex >= maxIndex || turning}
              aria-label="หน้าถัดไป"
              className="absolute right-1 top-1/2 z-20 -translate-y-1/2 rounded-full bg-white/10 p-2 text-white transition hover:bg-white/20 disabled:opacity-30 sm:right-3"
            >
              <ChevronRight className="h-6 w-6" />
            </button>
          </>
        )}
      </div>

      {ready ? (
        <div className="flex items-center justify-center gap-3 pb-4">
          <div
            className="inline-flex items-center rounded-full bg-white/10 p-0.5 sm:hidden"
            role="group"
            aria-label="สลับโหมดการดู"
          >
            <button
              type="button"
              onClick={() => setMode(1)}
              aria-pressed={perView === 1}
              className={`rounded-full px-2.5 py-1 text-xs font-medium transition ${
                perView === 1 ? "bg-white text-navy" : "text-white/80"
              }`}
            >
              1 หน้า
            </button>
            <button
              type="button"
              onClick={() => setMode(2)}
              aria-pressed={perView === 2}
              className={`rounded-full px-2.5 py-1 text-xs font-medium transition ${
                perView === 2 ? "bg-white text-navy" : "text-white/80"
              }`}
            >
              2 หน้า
            </button>
          </div>
          <p className="text-center text-xs text-white/60 sm:text-sm">{rangeLabel}</p>
        </div>
      ) : null}
    </div>,
    document.body,
  );
}

function PageFace({ page }: { page: FlipbookPage | undefined }) {
  if (!page) {
    return (
      <div className="h-full w-full flex-1 animate-pulse rounded-sm bg-white/10" />
    );
  }
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={page.url}
      alt=""
      className="h-full w-full flex-1 rounded-sm bg-white object-contain shadow-2xl"
    />
  );
}
