import type { QuoteLead } from "@/lib/leads/types";

function isoDaysAgo(days: number, hour = 10): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 15, 0, 0);
  return d.toISOString();
}

type DemoLead = QuoteLead & {
  assigneeId: string | null;
  assigneeName: string | null;
};

/** 10 mock quotation leads for admin UI when API has no rows yet. */
export const DEMO_LEADS: DemoLead[] = [
  {
    id: "demo-lead-01",
    source: "quote",
    status: "new",
    contactName: "คุณสมชาย ใจดี",
    jobTitle: "เจ้าของบ้าน",
    phone: "081-234-5678",
    contactType: "บุคคลธรรมดา",
    businessName: null,
    installAddress: "ลาดพร้าว กรุงเทพฯ",
    billingAddress: null,
    taxId: null,
    email: "somchai@example.com",
    productType: "ผ้าม่าน",
    requestedSize: "หน้าต่างห้องนั่งเล่น 3 บาน",
    siteImageName: null,
    siteImageUrl: null,
    callbackDate: "2026-08-05",
    referralSource: "Google",
    note: "ต้องการโทนครีม-เทา",
    assigneeId: "staff-sales-01",
    assigneeName: "เซลล์โส",
    createdAt: isoDaysAgo(0, 9),
    updatedAt: isoDaysAgo(0, 9),
  },
  {
    id: "demo-lead-02",
    source: "quote",
    status: "contacted",
    contactName: "คุณนภา สุขใจ",
    phone: "089-111-2233",
    contactType: "บุคคลธรรมดา",
    installAddress: "นนทบุรี",
    email: "napa@example.com",
    productType: "มู่ลี่",
    requestedSize: "มู่ลี่ไม้ ห้องนอน",
    referralSource: "Facebook",
    note: "นัดวัดหน้างานวันเสาร์",
    assigneeId: "staff-sales-02",
    assigneeName: "เชลล์ตุ่น",
    createdAt: isoDaysAgo(1, 11),
    updatedAt: isoDaysAgo(1, 14),
  },
  {
    id: "demo-lead-03",
    source: "quote",
    status: "quoted",
    contactName: "คุณอรุณ บ้านสวย",
    jobTitle: "ผู้จัดการ",
    phone: "02-123-4567",
    contactType: "นิติบุคคล",
    businessName: "บจก.บ้านสวย",
    installAddress: "บางนา กรุงเทพฯ",
    billingAddress: "บางนา กรุงเทพฯ",
    taxId: "0105551234567",
    email: "office@baansuai.example",
    productType: "ม่านม้วน",
    requestedSize: "ออฟฟิศชั้น 3",
    referralSource: "LINE",
    note: "ส่งใบเสนอราคาแล้ว รอคอนเฟิร์ม",
    assigneeId: "staff-sales-03",
    assigneeName: "เชลล์โจ้",
    createdAt: isoDaysAgo(1, 15),
    updatedAt: isoDaysAgo(0, 16),
  },
  {
    id: "demo-lead-04",
    source: "quote",
    status: "won",
    contactName: "คุณอารี พร้อม",
    phone: "086-555-7788",
    contactType: "บุคคลธรรมดา",
    installAddress: "พระราม 5 นนทบุรี",
    email: "aree@example.com",
    productType: "ม่านปรับแสง",
    requestedSize: "บานใหญ่โถง",
    referralSource: "เพื่อนแนะนำ",
    note: "ปิดการขายแล้ว",
    assigneeId: "staff-sales-04",
    assigneeName: "เชลล์เฟิร์น",
    createdAt: isoDaysAgo(2, 10),
    updatedAt: isoDaysAgo(1, 12),
  },
  {
    id: "demo-lead-05",
    source: "quote",
    status: "new",
    contactName: "คุณวิชัย รุ่งเรือง",
    phone: "092-887-1111",
    contactType: "ร้านค้า/ธุรกิจ",
    businessName: "ร้านวิชัยพาณิชย์",
    installAddress: "คลองสามวา กรุงเทพฯ",
    email: "wichai@example.com",
    productType: "ฉากกั้นห้อง",
    requestedSize: "กั้นแอร์ 2 ห้อง",
    referralSource: "Instagram",
    note: null,
    assigneeId: null,
    assigneeName: null,
    createdAt: isoDaysAgo(2, 18),
    updatedAt: isoDaysAgo(2, 18),
  },
  {
    id: "demo-lead-06",
    source: "contact",
    status: "contacted",
    contactName: "คุณฝัน โชว์รูม",
    phone: "080-064-8918",
    contactType: "บุคคลธรรมดา",
    installAddress: "โชว์รูมช่างตี๋",
    email: "fun@example.com",
    productType: "วอลเปเปอร์",
    requestedSize: "ผนังห้องนั่งเล่น",
    referralSource: "ผ่านหน้างาน/โชว์รูม",
    note: "แวะดูตัวอย่างที่โชว์รูมแล้ว",
    assigneeId: "staff-sales-05",
    assigneeName: "เชลล์ฝัน",
    createdAt: isoDaysAgo(3, 13),
    updatedAt: isoDaysAgo(2, 9),
  },
  {
    id: "demo-lead-07",
    source: "quote",
    status: "quoted",
    contactName: "คุณปทุม ผ้าม่าน",
    jobTitle: "เจ้าของร้าน",
    phone: "094-216-3761",
    contactType: "ร้านค้า/ธุรกิจ",
    businessName: "ร้านผ้าม่านปทุม",
    installAddress: "ปทุมธานี",
    email: "pathum@example.com",
    productType: "ม่านไฟฟ้า",
    requestedSize: "มอเตอร์ผ้าม่าน 4 ชุด",
    referralSource: "Google",
    note: "ขอราคา B2B",
    assigneeId: "staff-sales-02",
    assigneeName: "เชลล์ตุ่น",
    createdAt: isoDaysAgo(3, 16),
    updatedAt: isoDaysAgo(2, 11),
  },
  {
    id: "demo-lead-08",
    source: "quote",
    status: "cancelled",
    contactName: "คุณกิตติ วงศ์",
    phone: "081-550-8044",
    contactType: "บุคคลธรรมดา",
    installAddress: "สมุทรปราการ",
    email: "kitti@example.com",
    productType: "ฟิล์มอาคาร",
    requestedSize: "คอนโด 2 ห้อง",
    referralSource: "Facebook",
    note: "ลูกค้าเลื่อนโปรเจกต์",
    cancelReason: "ลูกค้าเลื่อนโปรเจกต์ออกไปไม่มีกำหนด — ขอเก็บรายชื่อไว้ก่อน",
    cancelImageName: null,
    cancelImageUrl: null,
    assigneeId: "staff-sales-01",
    assigneeName: "เซลล์โส",
    createdAt: isoDaysAgo(4, 12),
    updatedAt: isoDaysAgo(3, 10),
  },
  {
    id: "demo-lead-09",
    source: "fab",
    status: "won",
    contactName: "คุณมณี สว่าง",
    phone: "097-949-8645",
    contactType: "บุคคลธรรมดา",
    installAddress: "รามอินทรา กรุงเทพฯ",
    email: "manee@example.com",
    productType: "ผ้าม่าน",
    requestedSize: "ทั้งบ้าน",
    referralSource: "LINE",
    note: "ติดตั้งเสร็จแล้ว",
    assigneeId: "staff-sales-03",
    assigneeName: "เชลล์โจ้",
    createdAt: isoDaysAgo(5, 9),
    updatedAt: isoDaysAgo(1, 17),
  },
  {
    id: "demo-lead-10",
    source: "quote",
    status: "new",
    contactName: "คุณโอ๋ คอนโด",
    phone: "092-887-4288",
    contactType: "บุคคลธรรมดา",
    installAddress: "อโศก กรุงเทพฯ",
    email: "oh@example.com",
    productType: "ม่านม้วน",
    requestedSize: "คอนโด 1 ห้องนอน",
    referralSource: "Google",
    note: "สนใจม่านม้วนคอนโด",
    assigneeId: null,
    assigneeName: null,
    createdAt: isoDaysAgo(6, 20),
    updatedAt: isoDaysAgo(6, 20),
  },
];
