import type { JobApplication } from "@/lib/careers/types";

export const DEMO_APPLICATIONS: JobApplication[] = [
  {
    id: "app-demo-1",
    jobPostingId: "job-1",
    jobTitle: "ช่างเย็บผ้าม่าน",
    fullName: "คุณวิชัย ขยันงาน",
    phone: "0811112222",
    email: "wichai@example.com",
    lineId: "wichai_sew",
    address: "เขตคลองสามวา กรุงเทพฯ",
    education: "มัธยมศึกษา / ปวช.",
    experienceNote: "เย็บผ้าม่านมา 3 ปี ที่โรงงานผ้าม่านแห่งอื่น",
    coverNote: null,
    expectedSalary: "500 บาท/วัน",
    availableFrom: null,
    resumeFileName: "resume-wichai.pdf",
    resumeFilePath: null,
    resumeSignedUrl: null,
    portfolioFiles: [
      {
        name: "ผลงานเย็บม่าน-01.png",
        path: null,
        signedUrl: "/images/careers/sew.png",
      },
    ],
    status: "new",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "app-demo-2",
    jobPostingId: null,
    jobTitle: null,
    fullName: "คุณสุดา รักงาน",
    phone: "0833334444",
    email: "suda@example.com",
    lineId: null,
    address: "เขตบางเขน กรุงเทพฯ",
    education: "ปริญญาตรี",
    experienceNote: "เคยทำงานฝ่ายขายเฟอร์นิเจอร์ 2 ปี",
    coverNote: "สนใจร่วมงานฝ่ายขายหรือธุรการ ยังไม่เห็นตำแหน่งที่ตรงในตอนนี้",
    expectedSalary: "ตามตกลง",
    availableFrom: null,
    resumeFileName: "resume-suda.pdf",
    resumeFilePath: null,
    portfolioFiles: [],
    status: "new",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
