import type { FactoryVisitBooking } from "@/lib/visits/types";

export const DEMO_VISITS: FactoryVisitBooking[] = [
  {
    id: "visit-demo-1",
    fullName: "คุณสมชาย ใจดี",
    phone: "0812345678",
    email: "somchai@example.com",
    lineId: "somchai_line",
    businessName: "บริษัท ตัวอย่าง จำกัด",
    contactPosition: "ผู้จัดการฝ่ายจัดซื้อ",
    taxId: "0105551234567",
    visitSites: ["blinds", "curtain"],
    companyProfileName: "company-profile.pdf",
    companyProfileUrl: "/images/factory/visit-01-production.png",
    businessCardName: "namecard.jpg",
    businessCardUrl: "/images/careers/sew.png",
    visitDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)
      .toISOString()
      .slice(0, 10),
    session: "morning",
    visitorCount: 3,
    bookingKind: "factory-visit",
    purpose: "พาลูกค้า/ผู้บริหารเยี่ยมชมก่อนสั่งผลิต",
    productInterest: "ม่านไฟฟ้า",
    note: null,
    status: "pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "visit-demo-2",
    fullName: "คุณพรทิพย์ วงศ์สุข",
    phone: "0898765432",
    email: null,
    lineId: "porntip99",
    businessName: "ร้านผ้าม่านวงศ์สุข",
    contactPosition: "เจ้าของกิจการ",
    taxId: "0105559876543",
    visitSites: ["blinds", "partition", "curtain"],
    companyProfileName: null,
    businessCardName: "card.png",
    businessCardUrl: "/images/careers/sew.png",
    visitDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)
      .toISOString()
      .slice(0, 10),
    session: "evening",
    visitorCount: 1,
    purpose: "ดูตัวอย่างสินค้า/โชว์รูมโรงงาน",
    productInterest: "ผ้าม่าน",
    note: "สะดวกเฉพาะช่วงเย็นวันธรรมดา",
    bookingKind: "factory-visit",
    status: "confirmed",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "visit-demo-3",
    bookingKind: "product-presentation",
    fullName: "คุณศิริพร อรุณรุ่ง",
    phone: "0861112233",
    email: "siriporn@corp.example",
    lineId: "siri_purchase",
    businessName: "บริษัท คอร์ปอเรท โฮลดิ้ง จำกัด",
    contactPosition: "ผู้จัดการฝ่ายจัดซื้อ",
    department: "จัดซื้อ",
    taxId: "0105561234568",
    legalEntityType: "บริษัทจำกัด",
    industry: "ออฟฟิศ / สำนักงาน",
    officeAddress: "88 อาคารสาทร กรุงเทพฯ",
    visitSites: [],
    presentationVenue: "company",
    venueAddress: "อาคารสาทร ชั้น 18 ห้องประชุม A",
    jobType: "ออฟฟิศใหม่",
    decisionTimeline: "ภายใน 1 เดือน",
    estimatedScope: "ประมาณ 40 บาน",
    companyProfileName: "corp-profile.pdf",
    companyProfileUrl: "/images/factory/visit-02-blinds.png",
    businessCardName: "siriporn-card.jpg",
    businessCardUrl: "/images/careers/sew.png",
    visitDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)
      .toISOString()
      .slice(0, 10),
    session: "morning",
    visitorCount: 4,
    purpose: "นัดนำเสนอสินค้า · ทีมเข้าพบที่บริษัท",
    productInterest: "ผ้าม่าน, ม่านม้วน, ม่านไฟฟ้า",
    note: "ต้องมีใบเข้าอาคารล่วงหน้า",
    status: "pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
